[build]
builder = "NIXPACKS"
buildCommand = "./gradlew build -x test"

[deploy]
startCommand = "java -Xms128m -Xmx256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/posts"
healthcheckTimeout = 60
